stages:
  - deploy

frontend-build-deploy-prod:
  stage: deploy
  script:
    - echo "in frontend-deploy-prod job"
    - rsync -avh frontend/ deployer@127.0.0.1:~/ema/frontend/
    - >
      ssh deployer@127.0.0.1 "
      . ~/.profile &&
      . ~/.bashrc &&
      . ~/.nvm/nvm.sh &&
      node -v &&
      cd ema/frontend &&
      npm install &&
      pm2 restart app.js"
  tags:
    - ema
  rules:
    - if: $CI_COMMIT_BRANCH == "production"
      changes:
        - frontend/**/*

backend-build-deploy-prod:
  stage: deploy
  script:
    - echo "in backend-deploy-prod job"
  tags:
    - ema
  rules:
    - if: $CI_COMMIT_BRANCH == "production"
      changes:
        - backend/**/*
