stages:
  - deploy

frontend-build-deploy-prod:
  stage: deploy
  script:
    - echo "in frontend-deploy-prod job"
    - ssh deployer@127.0.0.1 bash <<EOF
      node -v
      npm -v
      EOF
  tags:
    - ema
  rules:
    - if: $CI_COMMIT_BRANCH == "production"
      changes:
        - frontend/**/*

backend-build-deploy-prod:
  stage: deploy
  script:
    - echo "in backend-deploy-prod job"
  tags:
    - ema
  rules:
    - if: $CI_COMMIT_BRANCH == "production"
      changes:
        - backend/**/*
